---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fe-alinea
  namespace: fe-alinea
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~3.0
spec:
  releaseName: fe-alinea
  chart:
    git: git@github.pie.apple.com:kbatra/cicd.git
    ref: master
    path: charts/fe-alinea
  values:
    image:
      repository: 608150934281.dkr.ecr.us-west-2.amazonaws.com/test-cicd-repository
      tag: v1
    service:
      enabled: false
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:8080;
          proxy_hide_header l5d-remote-ip;
          proxy_hide_header l5d-server-id;
      path: /
      hosts:
      - fe-alinea.apple.com
